Gemfile, Gemfile.lock
=> add_font-awesome-sass

app/controllers/posts_controller.rb, app/models/post.rb, config/routes.rb, db/migrate/20190625102404_create_posts.rb, db/schema.rb
postコントローラー、モデルを生成した。
ルーティングとルートパスを設定した。
post周りのビューを完成させるため。
- 商品出品ページ
- 商品詳細ページ
- 商品購入確認ページ
=> Create post function

Gemfile, Gemfile.lock, config/unicorn.rb
gemfileにunicorn追加
config/unicorn.rb作成
EC2デプロイ用のAPPサーバ作成のため
=> insert_unicorn

app/assets/stylesheets/modules/mypage/mypage_main.scss, app/views/mypages/index.html.haml, app/views/shared/top_page/_app-banner.html.haml
ユーザーマイページに部分テンプレートを適用する
マイページにヘッダー、フッター、出品ボタンを表示するため
=> render-partial-template-in-user-mypage

app/assets/stylesheets/application.scss, app/assets/stylesheets/modules/mypage/logout.scss, app/controllers/mypages_controller.rb, app/views/mypages/logout.html.haml, config/routes.rb
ログアウトページを実装する
ログアウトページを表示できるようにするため
=> Create view of logout page

app/assets/stylesheets/application.scss, app/assets/stylesheets/modules/posts/buy.scss, app/controllers/posts_controller.rb, app/views/posts/buy.html.haml, config/routes.rb
商品購入確認ページのコーディング
以下、URL参照
https://gyazo.com/846a1863aaabeaf6153be97c099a0afa
必須機能のため
=> create buy post lastcheck

Gemfile, app/controllers/application_controller.rb, app/views/devise/registrations/new.html.haml, db/migrate/20190628051413_add_nickname_to_users.rb, db/schema.rb
Usersテーブルに
カラム nickname,avatar
を追加した。
=> add-column-devise

app/views/profiles/new_1.html.haml, app/views/shared/user_registration/_form-footer.html.haml, app/views/shared/user_registration/_form-header.html.haml
profiles/new_1.html.hamlのヘッダーとフッターを部分テンプレート化しました
=> Create partial template of form header and footer

app/assets/stylesheets/modules/shared/top_page/header.scss, app/views/devise/registrations/new.html.haml, app/views/devise/sessions/new.html.haml, app/views/devise/shared/_member_info.html.haml, app/views/profiles/new_7.html.haml, app/views/shared/top_page/_header.html.haml
ユーザの
ログイン機能、サインイン機能、ログアウト機能
を実装しました。
まだgemのデバイスを使用しているため
全て簡易な画面になっていますが、
商品機能の実装の際に必要なユーザ機能は
十分にあると考えております。
ご確認願います。
※ログアウトボタンは、開発のし易さの考慮して仮置きで入れております。
https://gyazo.com/d2db491e00921737966ebe6584cd8a0e
商品出品、今後の開発に必要な最低限の昨日の実装のため
ファイルパス | 機能
-- | --
sessions/new.html.erb | ログイン画面
registrations/new.html.erb | ユーザ登録画面
以上を編集して、
ビューを変更しました。
確認お願い致します。
https://gyazo.com/10e808a554e3b3bcc6c5a890bf80a106
=> add-user-login,logout,sign_in

Gemfile, Gemfile.lock, README.md, app/models/brand.rb, app/models/post.rb, config/application.rb, config/locales/ja.yml, db/migrate/20190628112226_add_column_to_post.rb, db/migrate/20190628113215_create_brands.rb, db/migrate/20190628113350_add_references_to_post.rb, db/schema.rb
商品出品機能に必要な機能を準備した。
- postsテーブルにカラムを追加
- brandモデル、テーブルを作成
- enumを定義
- gemをインストール
- enum_help
- postモデルに以下4項目のenumを記述
- サイズ
- 商品の状態
- 配送料の負担
- 発送までの日数
- デフォルトの英語表記を日本語表記に変換
- ja.ymlを作成
商品出品画面の実装に必要なため。
=> Create posts new function

db/migrate/20190630065650_add_column_to_addresses.rb, db/migrate/20190630065940_add_userid_to_addresses.rb, db/migrate/20190630071026_add_column_to_profiles.rb, db/migrate/20190630071752_add_userid_to_profiles.rb, db/migrate/20190630072025_add_column_to_creditcard.rb, db/migrate/20190630072422_add_userid_to_creditcard.rb, db/schema.rb
profiles、addresses、credit_cardsのカラム作成しました。
=> add_column

app/assets/stylesheets/modules/posts/new.scss, app/views/posts/new.html.haml, app/views/shared/posts_new/_product_detail.html.haml, app/views/shared/user_registration/_form-header.html.haml
①カテゴリーの見た目修正（hamlでclearfixの記述を削除する。）
②フッターとヘッターの追加
メルカリの表示画面と合わせるため。
=> Re create posts new

app/views/profiles/new_1.html.haml
profiles/new_1のビューを修正
hamlの構文エラーを修正するため
=> Fix first page of profiles

app/views/profiles/new_2.html.haml, config/locales/ja.yml
profiles以下のビューでエラーが出ている部分を修正
ユーザーの登録画面を正常に表示できるようにするため
=> Fix errors of profiles pages

README.md, app/controllers/posts_controller.rb, app/models/first_category.rb, app/models/post.rb, app/models/second_category.rb, app/views/shared/posts_new/_product_detail.html.haml, config/locales/ja.yml, db/migrate/20190630080933_change_column_to_post.rb, db/schema.rb
商品出品にかかるサーバーサイドの設定をした。
- ストロングパラメーター
- statusのenumを追加
- nill:falseからdefault:0に変更
- activehashを使ったカテゴリーの実装（仮）
createした時にカラムを埋めるため。
カテゴリーに関しては後からテーブルを実装予定のため仮でアクティブハッシュを使用。
=> Create posts new function2

app/controllers/posts_controller.rb, app/views/posts/new.html.haml, app/views/shared/posts_new/_delivery_detail.html.haml, app/views/shared/posts_new/_image_upload.html.haml, app/views/shared/posts_new/_post_btn.html.haml, app/views/shared/posts_new/_price_detail.html.haml, app/views/shared/posts_new/_product_detail.html.haml, app/views/shared/posts_new/_product_upload.html.haml, app/views/shared/user_registration/_form-header.html.haml, config/initializers/carrierwave.rb
formタグをform_forタグに変更。
投稿出品の登録に必要なため。
=> Create post new function 3

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/assets/javascripts/product_price.js, app/controllers/posts_controller.rb, app/views/shared/posts_new/_price_detail.html.haml
商品出品機能実装
- 価格表示部分にjsでイベントを追加した。
ユーザービリティ向上のため。
=> Create posts new function4

app/assets/stylesheets/modules/shared/top_page/sell-fix-logo.scss, app/controllers/posts_controller.rb, app/views/shared/posts_new/_delivery_detail.html.haml, app/views/shared/posts_new/_product_detail.html.haml, app/views/shared/top_page/_sell-fix-logo.html.haml
商品出品機能実装
- カテゴリーのフォームをcollection_selectに修正
- ストロングパラメーターにuser_idを追加
- 不要なインスタンスの記述を削除
- 出品ボタンのパスとz-indexを修正
postsテーブルにデータの保存ができるようにするため。
=> Create posts new function5

Gemfile, Gemfile.lock, app/assets/stylesheets/modules/shared/pankuzu.scss, app/views/layouts/application.html.haml, app/views/mypages/identification.html.haml, app/views/mypages/index.html.haml, app/views/mypages/logout.html.haml, app/views/posts/show.html.haml, config/breadcrumbs.rb
パンくずリスト機能を実装する
サービスの円滑な提供のため
[![Image from Gyazo](https://i.gyazo.com/87a60e6dc9fceb4669b0c1116df3e918.png)](https://gyazo.com/87a60e6dc9fceb4669b0c1116df3e918)
[![Image from Gyazo](https://i.gyazo.com/b54292883e352d202b59df2a233e2e00.png)](https://gyazo.com/b54292883e352d202b59df2a233e2e00)
[![Image from Gyazo](https://i.gyazo.com/35238d1e7489b36dbffff65ebbac4551.png)](https://gyazo.com/35238d1e7489b36dbffff65ebbac4551)
=> Breadcrumbs implementation

app/controllers/users/confirmations_controller.rb, app/controllers/users/omniauth_callbacks_controller.rb, app/controllers/users/passwords_controller.rb, app/controllers/users/registrations_controller.rb, app/controllers/users/sessions_controller.rb, app/controllers/users/unlocks_controller.rb, app/models/profile.rb, app/models/user.rb, app/views/devise/shared/_member_info.html.haml, config/initializers/carrierwave.rb, config/routes.rb, db/migrate/20190702051120_change_column_to_allow_null.rb, db/schema.rb
ユーザー登録ページの最初のページでuserとprofileを同時に登録できるようにする
ユーザー登録機能を完成させるため
=> Create user registration function1

README.md, app/controllers/posts_controller.rb, app/views/shared/posts_new/_product_detail.html.haml, db/migrate/20190702045723_add_name_to_brands.rb, db/migrate/20190702110845_addbrand_name_to_posts.rb, db/schema.rb
postsコントローラーから brandモデルに登録する。
商品登録機能に必要となるため。
=> add brand function

Gemfile, Gemfile.lock, app/models/post.rb
商品出品のバリデーションを実装した。
DBに正常な情報を登録するため。
=> Add validations

app/uploaders/image_uploader.rb, config/initializers/carrierwave.rb
画像をS３でアップロードできるようにした。
- carrierwave.rbのコメントアウトを外す
- uploaderのstrageをfogに変更
本番環境でAWSのS3に画像をアップするため。
=> Upload to s3

Gemfile, Gemfile.lock, app/controllers/posts_controller.rb, app/views/posts/show.html.haml, app/views/shared/top_page/_post-card.html.haml, config/breadcrumbs.rb, db/schema.rb, spec/rails_helper.rb
商品一覧ページの写真実装
商品詳細ページのパンくず実装
円滑なサービスの提供のため
[![Image from Gyazo](https://i.gyazo.com/0fe9b0744486a13a733290c24df0fc9a.png)](https://gyazo.com/0fe9b0744486a13a733290c24df0fc9a)
[![Image from Gyazo](https://i.gyazo.com/6b88be9248122757c94d6038b5f6d98e.png)](https://gyazo.com/6b88be9248122757c94d6038b5f6d98e)
=> implementation_items_list,breadcrumbs

app/assets/stylesheets/config/profiles/_member_info.scss, app/assets/stylesheets/config/profiles/_user_registration_secondhalf.scss, app/assets/stylesheets/config/profiles/backscreen.scss, app/assets/stylesheets/config/profiles/users.scss, app/views/devise/shared/_member_info.html.haml, app/views/profiles/_address.html.haml, app/views/profiles/_card.html.haml, app/views/profiles/new_4.html.haml, app/views/profiles/new_5.html.haml, app/views/profiles/new_6.html.haml
ユーザー登録ページのビューを修正
[![Image from Gyazo](https://i.gyazo.com/fad8d76d0c3f3319ba1ab559dc8fec14.gif)](https://gyazo.com/fad8d76d0c3f3319ba1ab559dc8fec14)
[![Image from Gyazo](https://i.gyazo.com/479028e5a9aeccf1ce6c02d19e24dcf5.gif)](https://gyazo.com/479028e5a9aeccf1ce6c02d19e24dcf5)
[![Image from Gyazo](https://i.gyazo.com/5847175e60a8f5741c7a80830dc6823f.gif)](https://gyazo.com/5847175e60a8f5741c7a80830dc6823f)
ビューが著しく崩れていたため
=> Fix view of user registration

Gemfile, Gemfile.lock, app/models/image.rb, app/models/post.rb, app/uploaders/image_uploader.rb, config/environments/production.rb, config/storage.yml
=> return_yesterday

app/assets/javascripts/image_upload.js, app/assets/stylesheets/application.scss, app/assets/stylesheets/mixins/posts_new/image_btn.scss, app/assets/stylesheets/modules/shared/posts_new/image_upload.scss, app/controllers/posts_controller.rb, app/views/shared/posts_new/_image_upload.html.haml, config/application.rb
商品出品画面の画像プレビュー表示を非同期で再現。
※レイアウト表示、プレビュー編集、create機能のみ。
プレビュー削除と実際のプレビュー表示は別ブランチで実装予定
ユーザービリティ向上のため。
=> Add image upload jquery

app/controllers/posts_controller.rb, app/views/posts/done.html.haml, app/views/posts/show.html.haml, app/views/posts/transaction.html.haml, config/routes.rb
Pay.jpを使用した商品購入機能を実装した。
- 商品の購入画面
[![Image from Gyazo](https://i.gyazo.com/7303380b57b8a911ff9bbd75f51255b5.gif)](https://gyazo.com/7303380b57b8a911ff9bbd75f51255b5)
- pay.jpの画面
必須機能のため
=> create buy function

app/assets/stylesheets/config/profiles/users.scss, app/controllers/address_controller.rb, app/controllers/address_session_controller.rb, app/controllers/profiles_controller.rb, app/controllers/user_session_controller.rb, app/controllers/users/registrations_controller.rb, app/models/user.rb, app/views/address/_address.html.haml, app/views/devise/shared/_member_info.html.haml, app/views/shared/user_registration/_error.html.haml, app/views/users/done.haml, config/locales/ja.yml
ユーザー登録画面のエラーメッセージを表示できるようにする
※ 住所情報入力画面のビューは別ブランチで修正
バリデーションエラーで弾かれた際にわかりやすくするため
=> Show error message in user registration view

app/assets/stylesheets/application.scss, app/assets/stylesheets/modules/mypage/telephone_number.scss, app/views/mypages/edit.html.haml, app/views/mypages/telephone_number.html.haml, config/breadcrumbs.rb, config/routes.rb
Mypageの電話番号の確認ページの実装と、Mypageのプロフィールページのパンくずリストの実装
サービスの提供に必須の機能であるため
[![Image from Gyazo](https://i.gyazo.com/d65d17b189a1f84fe9d6607118fd5033.png)](https://gyazo.com/d65d17b189a1f84fe9d6607118fd5033)
[![Image from Gyazo](https://i.gyazo.com/26a92fe33ed61c0df130d16edc1cf9f1.png)](https://gyazo.com/26a92fe33ed61c0df130d16edc1cf9f1)
=> Phone number confirmation and breadcrumb implementation

app/assets/stylesheets/config/profiles/_member_info.scss, app/assets/stylesheets/config/profiles/_user_registration.scss, app/assets/stylesheets/config/profiles/_user_registration_secondhalf.scss, app/assets/stylesheets/config/profiles/backscreen.scss, app/assets/stylesheets/config/profiles/users.scss, app/views/profiles/new.html.haml, app/views/users/sms_confirmation.html.haml
ユーザー登録機能の一連のビューの、崩れている部分を修正
- エラーメッセージを表示した際の住所情報登録画面
[![Image from Gyazo](https://i.gyazo.com/b91e9caa53f1ecda534cee2d97e6887b.gif)](https://gyazo.com/b91e9caa53f1ecda534cee2d97e6887b)
- 電話番号認証ページ
[![Image from Gyazo](https://i.gyazo.com/0b2e3cb075aa652dcb63097fd5f0391d.png)](https://gyazo.com/0b2e3cb075aa652dcb63097fd5f0391d)
- エラーメッセージを表示した際に崩れたため
- 見やすくするため
=> Fix view of user registration2

app/controllers/users/registrations_controller.rb
ユーザー情報登録後にサインインした状態にする記述を追加
ユーザー登録後にログインされた状態でトップページに遷移させるため
=> Add function of sign in after sign up

app/models/address.rb, app/models/profile.rb, config/locales/ja.yml
ユーザー登録時のバリデーションを追加
より正確な情報をDBに保存するため
=> Add validation of user registration

app/views/mypages/logout.html.haml, app/views/shared/mypage/_side_menu.html.haml
ログアウトページからログアウトできるようにする
本物のメルカリの仕様と合わせるため
=> Add sign out function

app/controllers/mypages_controller.rb, app/controllers/profiles_controller.rb, app/views/mypages/card.html.haml, app/views/shared/mypage/_side_menu.html.haml, db/schema.rb
プロフィール編集のルーティングを変更する。
プロフィール編集が必要になるため。
=> edit profile change routing

app/assets/stylesheets/modules/mypage/identification.scss, app/views/mypages/identification.html.haml, app/views/shared/mypage/_side_menu.html.haml
・本人情報登録ページへのリンクの設定
・ビューの微調整
マイページから本人情報ページに遷移できるようにするため
=> Add link to user registration information

app/assets/stylesheets/application.scss, app/assets/stylesheets/config/profiles/backscreen.scss, app/assets/stylesheets/config/profiles/credit-card-registration.scss, app/assets/stylesheets/config/profiles/users.scss, app/controllers/users/registrations_controller.rb, app/views/address/_address.html.haml, app/views/credit_card/_credit-card.html.haml, app/views/credit_card/new.html.haml
ユーザー登録ページのビューを修正
他のページと見た目に差があったため
=> Fix view of user registration3

app/controllers/mypages_controller.rb, app/views/mypages/card.html.haml, app/views/mypages/email_password.html.haml, app/views/mypages/logout.html.haml, app/views/mypages/profile.html.haml, app/views/mypages/telephone_number.html.haml, app/views/shared/mypage/_side_menu.html.haml, app/views/shared/top_page/_header.html.haml, config/breadcrumbs.rb
ユーザー情報のルーティングとパスの整理
ユーザー情報編集のため。
=> through pass

app/assets/stylesheets/application.scss, app/assets/stylesheets/modules/posts/transaction.scss, app/controllers/posts_controller.rb, app/views/credit_card/confirmation.html.haml, app/views/credit_card/edit.html.haml, app/views/credit_card/show.html.haml, app/views/posts/transaction.html.haml, app/views/shared/mypage/_side_menu.html.haml
クレジットカードが登録されているかどうかで、購入ボタンの変更。
- クレジットカード登録済み
[![Image from Gyazo](https://i.gyazo.com/03964e76c8480b09301428d375b3adc6.png)](https://gyazo.com/03964e76c8480b09301428d375b3adc6)
- クレジットカード未登録
[![Image from Gyazo](https://i.gyazo.com/c4bba3c4a9e77706d720fd16adf74c1f.png)](https://gyazo.com/c4bba3c4a9e77706d720fd16adf74c1f)
メルカリの仕様に合わせるため
=> Edit buy view

app/controllers/profiles_controller.rb, app/controllers/users/omniauth_callbacks_controller.rb, app/models/user.rb, app/views/devise/registrations/new.html.haml, app/views/devise/shared/_member_info.html.haml, app/views/profiles/new.html.haml
SNS認証機能の実装
sessionを使用して、新規登録の際に画面が遷移するよう実装
※ ログイン機能は前回実装済み
[![Image from Gyazo](https://i.gyazo.com/5ec685eda6c4344d6430992164b09a3f.gif)](https://gyazo.com/5ec685eda6c4344d6430992164b09a3f)
前回未完了だったため
SNS認証は完了必須機能のため
=> Setting omniauth sns login function2

app/views/devise/confirmations/new.html.haml, app/views/devise/passwords/edit.html.haml, app/views/devise/passwords/new.html.haml, app/views/devise/registrations/edit.html.haml, app/views/devise/shared/_error_messages.html.haml, app/views/devise/unlocks/new.html.haml, app/views/shared/mypage/_side_menu.html.haml, config/locales/ja.yml
ユーザーのメールアドレスとパスワードを変更する機能を実装
メールアドレスの変更やパスワードの変更に対応できるようにするため
=> Add edit user information function

app/assets/javascripts/category.js, app/assets/javascripts/delivery_method.js, app/assets/javascripts/size_and_brand.js, app/views/shared/posts/form/_delivery_detail.html.haml, app/views/shared/posts/form/_product_detail.html.haml
商品出品画面のフォームの非同期部分を修正した。
- product_sizeフォームのname属性が誤っていたので修正
- category.jsにサイズとブランドフォームの記述も入っていたので別ファイルに分割
- newでは非同期で出現するフォームをeditでは最初から表示されるよう、ビューを編集
正しくcreateやupdateができるようにする為。
=> Modify jquery form

app/assets/javascripts/category.js, app/assets/stylesheets/application.scss, app/assets/stylesheets/modules/posts/show.scss, app/assets/stylesheets/modules/shared/posts/show/edit-box.scss, app/assets/stylesheets/modules/shared/posts/show/other-posts.scss, app/assets/stylesheets/modules/shared/posts/show/sns.scss, app/controllers/posts_controller.rb, app/models/post.rb, app/views/posts/show.html.haml, app/views/shared/posts/show/_edit-box.html.haml, app/views/shared/posts/show/_other-posts.html.haml, app/views/shared/posts/show/_sns.html.haml, app/views/shared/posts/show/_table.html.haml
show.html.hamlの細かい部分を修正した。
- 前後postのリンクにDBを適用
- ブランド、発送方法にDBを適用
- カテゴリー部分の修正
- 記述が長くなったので部分テンプレート化
- 不要CSSの削除
DBと紐付け完成形に近づける為。
=> Modify post show.html

app/assets/stylesheets/modules/mypage/card.scss, app/assets/stylesheets/modules/mypage/create_card.scss, app/assets/stylesheets/modules/mypage/mypage_main.scss, app/assets/stylesheets/modules/mypage/profile.scss, app/controllers/mypages_controller.rb, app/controllers/profiles_controller.rb, app/views/mypages/email_password.html.haml, app/views/mypages/profile.html.haml, config/initializers/carrierwave.rb, config/routes.rb, db/schema.rb
profileページのマックアップ及び編集機能の実装。
登録情報の修正を行う際に必須となる機能です。
[![Image from Gyazo](https://i.gyazo.com/d163874a96d6ea4c26bb7ffaeccd60ce.gif)](https://gyazo.com/d163874a96d6ea4c26bb7ffaeccd60ce)
=> Create edit profile view

app/assets/stylesheets/modules/mypage/deliver_address.scss, app/assets/stylesheets/modules/mypage/identification.scss, app/controllers/profiles_controller.rb, app/views/mypages/identification.html.haml, app/views/profiles/edit_address_delivery.html.haml, config/routes.rb, db/schema.rb
マイページの「発送元・お届け先住所変更」「本人情報」ページの画面、機能の作成
=> Edit profile function

app/assets/stylesheets/application.scss, app/assets/stylesheets/config/posts/show/colors.scss, app/assets/stylesheets/mixins/posts/show/btn_styles.scss, app/assets/stylesheets/mixins/status_logo.scss, app/assets/stylesheets/modules/posts/show.scss, app/assets/stylesheets/modules/shared/posts/show/buy_button.scss, app/assets/stylesheets/modules/shared/status_logo.scss, app/views/posts/show.html.haml, app/views/shared/_status_logo.html.haml, app/views/shared/posts/show/_buy_button.html.haml
[![Image from Gyazo](https://i.gyazo.com/1d3527979e0f4bde4df6b3aa94c43f21.gif)](https://gyazo.com/1d3527979e0f4bde4df6b3aa94c43f21)
[![Image from Gyazo](https://i.gyazo.com/0ff6afffa1f60edec374f127bc47d561.png)](https://gyazo.com/0ff6afffa1f60edec374f127bc47d561)
ステータスを分かりやすくする為。
=> Create status logo

app/views/credit_card/confirmation.html.haml, app/views/devise/registrations/edit.html.haml, app/views/mypages/completed_transaction.html.haml, app/views/mypages/in_transaction.html.haml, app/views/mypages/listing.html.haml, app/views/mypages/logout.html.haml, app/views/mypages/profile.html.haml, app/views/mypages/purchase.html.haml, app/views/mypages/purchased.html.haml, app/views/mypages/telephone_number.html.haml, app/views/profiles/edit_address_delivery.html.haml, config/breadcrumbs.rb
マイページパンくずリストの実装
サービスの円滑な提供のため
[![Image from Gyazo](https://i.gyazo.com/17eb0bb52828987ea4291771a12c1b2e.png)](https://gyazo.com/17eb0bb52828987ea4291771a12c1b2e)
=> Breadcrumbs

spec/factories/users.rb, spec/models/user_spec.rb
ユーザー登録の際のバリデーションのテストコードを記述
※profile、addressは別ブランチでテストします
想定通りの動きをするかどうか確かめるため
=> Test validation when user registration function

app/assets/javascripts/image_upload.js
出品の際の画像投稿機能を編集した。
- どの削除ボタンが押されても新たに追加ができるよう改良
最後尾の削除ボタンが押された時でないと正常な動作ができない状態になっていたため。
[![Image from Gyazo](https://i.gyazo.com/f9c1f59f223b2929cc7c240b3783695a.gif)](https://gyazo.com/f9c1f59f223b2929cc7c240b3783695a)
=> edit-file-upload-function

app/controllers/posts_controller.rb
ポスト編集ページ遷移を可能にする。
投稿後の画像遷移のため。
=> add user links

app/assets/javascripts/image_upload.js, app/assets/stylesheets/modules/shared/posts/form/image_upload.scss, app/views/posts/edit.html.haml, app/views/shared/posts/edit/_image_upload.html.haml, app/views/shared/posts/edit/_images.html.haml, app/views/shared/posts/edit/_previews.html.haml, app/views/shared/posts/form/_image_upload.html.haml, db/schema.rb
商品編集画面の画像削除・追加機能を実装した。
画像のみ編集ができない状態になっていたため。
[![Image from Gyazo](https://i.gyazo.com/814a9533d81f66040b5ff4d23d2b364a.gif)](https://gyazo.com/814a9533d81f66040b5ff4d23d2b364a)
=> Edit post function

spec/factories/profiles.rb, spec/models/profile_spec.rb
ユーザー登録時のprofileモデルのバリデーションに対してテストを実施
期待通りの動作をするか確かめるため
=> Test validation when profile registration

app/models/address.rb, spec/factories/addresses.rb, spec/models/address_spec.rb
addressモデルのバリデーションテストを行う
期待通りの結果になるか確かめるため
=> Test validation of address model

app/assets/stylesheets/application.scss, app/assets/stylesheets/modules/category/index.scss, app/controllers/categories_controller.rb, app/views/categories/index.html.haml, config/routes.rb
カテゴリー機能を実装する。
メルカリのオプション機能であるため。
[![Image from Gyazo](https://i.gyazo.com/3210007e2086370332cb14451c4333d9.gif)](https://gyazo.com/3210007e2086370332cb14451c4333d9)
=> category_function

app/assets/stylesheets/application.scss, app/assets/stylesheets/modules/category/index.scss, app/controllers/categories_controller.rb, app/views/categories/index.html.haml, app/views/shared/top_page/_header.html.haml, config/routes.rb
カテゴリーページのマークアップを行う。
カテゴリー機能に必要となるため。
=> category page markup

app/controllers/categories_controller.rb, app/views/categories/index.html.haml
カテゴリーページへのリンクを変更。
トップページからの遷移のために必要となるため。
=> change link

app/controllers/posts_controller.rb, app/views/posts/search.html.haml, app/views/shared/top_page/_header.html.haml, config/breadcrumbs.rb, config/routes.rb
検索機能とパンくずリストの実装
サービスの提供に必須の機能であるため
[![Image from Gyazo](https://i.gyazo.com/64d23bebc5cd4230e9b64b5ad5a334c5.png)](https://gyazo.com/64d23bebc5cd4230e9b64b5ad5a334c5)
=> Search implementation

app/views/shared/mypage/_side_menu.html.haml, app/views/shared/top_page/_header.html.haml
デプロイ環境でのリンク変更
デプロイ環境でリンクパスが正しく動くようにするため。
=> change links

app/views/categories/index.html.haml, config/breadcrumbs.rb
カテゴリー一覧のパンくずリストをコメントアウトした
自動デプロイ後カテゴリー一覧ページがアクセスできなくなったため
=> hidden breadcrumbs

app/controllers/credit_card_controller.rb
サイドバーからのクレジットカード登録ページへのリンクを実装する。

ページ遷移に必要となるため。
=> set user params

app/views/mypages/identification.html.haml, app/views/shared/mypage/_side_menu.html.haml
=> Remove unnecessary code

app/assets/javascripts/brand.js, app/assets/javascripts/category.js, app/assets/javascripts/product_size.js, app/assets/javascripts/size_and_brand.js, app/controllers/posts_controller.rb, app/models/post.rb, app/views/posts/child_category.json.jbuilder, app/views/posts/grandchild_category.json.jbuilder, app/views/posts/show.html.haml, app/views/shared/posts/form/_product_detail.html.haml, app/views/shared/posts/show/_table.html.haml, config/routes.rb
商品周り各箇所にカテゴリーを適用させた。
- 出品画面のフォームを編集
- 選択された親カテゴリーに応じて子、孫のoptionを変更
- 選択された親カテゴリーに応じてブランド、サイズのフォームを出現させる
- 商品詳細ページでの表示
- 出品商品のカテゴリーを表示
- 「その他の商品」をブランドの有無により分岐して表示
カテゴリー関連が仮作成のままだったため。
[![Image from Gyazo](https://i.gyazo.com/97af414f3eda75e58248df58d47e6189.gif)](https://gyazo.com/97af414f3eda75e58248df58d47e6189)
=> Add category function

app/models/post.rb
カテゴリーのアソシエーションを見直した。
従来のアソシエーションのままだと出品できない状態になっていたため。
=> modify-category-function

app/controllers/credit_card_controller.rb, app/controllers/posts_controller.rb, app/controllers/users/registrations_controller.rb, app/views/address/_address.html.haml, app/views/credit_card/_credit_card2.html.haml, app/views/credit_card/confirmation.html.haml, app/views/credit_card/new.html.haml, app/views/posts/card.html.haml, app/views/posts/transaction.html.haml, config/routes.rb
クレジット情報登録の微調整を行なった。
修正内容を以下に示す。
１）商品購入確定画面からクレジットカードの登録ができるように修正
　[![Image from Gyazo](https://i.gyazo.com/d0ef2c3b0465c56a4c71644cc834e848.gif)](https://gyazo.com/d0ef2c3b0465c56a4c71644cc834e848)
2）新規登録からクレジットカードを登録できるように修正
[![Image from Gyazo](https://i.gyazo.com/5517d4ba8125d3d883e120d76398978b.gif)](https://gyazo.com/5517d4ba8125d3d883e120d76398978b)
３）マイページからクレジットカード登録の修正
　　→jsが一発目から聞くように修正
メルカリを企業様宛に出すように修正する必要があったため
=> Fixed credit card information

app/views/shared/posts/show/_buy_button.html.haml, app/views/shared/posts/show/_edit-box.html.haml
商品のステータスによって表示されるボタンを修正。
修正のため。
=> modify sold posts status

app/assets/javascripts/scroll_category.js, app/views/categories/index.html.haml
カテゴリーページ内リンクの実装
ページ内の機能のため。
[![Image from Gyazo](https://i.gyazo.com/3386f2ea2e441289695e2cbc3b2fab31.gif)](https://gyazo.com/3386f2ea2e441289695e2cbc3b2fab31)
=> Category function

app/controllers/profiles_controller.rb
updateのバグの修正
ユーザーを引き渡すのを忘れていたため。
=> change update

app/assets/stylesheets/modules/posts/transaction.scss, app/views/posts/transaction.html.haml
購入確認ページのビューの修正
ヘッダーとフッターが崩れていたため。
=> modify transaction view

app/controllers/posts_controller.rb, app/controllers/profiles_controller.rb, app/views/posts/done.html.haml, app/views/posts/index.html.haml
購入後画面の修正
・topページへの戻り（ヘッダ）
・購入商品情報の反映
=> edit_buy_done

app/views/shared/top_page/_post-card.html.haml
トップページのソールドアウト表示
トップページのソールドアウト表示
=> update post card

app/assets/stylesheets/config/profiles/_edit_profile.scss, app/controllers/users/sessions_controller.rb, app/views/devise/sessions/new.html.haml, app/views/devise/shared/_login_blank_error.html.haml, app/views/devise/shared/_login_error.html.haml, config/locales/ja.yml
ログイン失敗時のエラーメッセージを表示する
[![Image from Gyazo](https://i.gyazo.com/3042a6c970bf554b967e5cbb3329c30a.png)](https://gyazo.com/3042a6c970bf554b967e5cbb3329c30a)
[![Image from Gyazo](https://i.gyazo.com/473c6466d98e4833b4fc3b3a26bb24a3.png)](https://gyazo.com/473c6466d98e4833b4fc3b3a26bb24a3)
ログインできているかどうか、なぜログインできなかったのかをわかりやすくするため
=> Display error message of login page

app/assets/stylesheets/config/profiles/_edit_profile.scss, app/controllers/users/sessions_controller.rb, app/views/devise/sessions/new.html.haml, app/views/devise/shared/_login_check_box_error.html.haml, config/locales/ja.yml
ログインページのエラーメッセージ表示機能を修正
ロボットではありませんをチェックしない場合にうまくエラーメッセージが表示されないため
=> Modify display error message function in sign in page

app/assets/stylesheets/config/profiles/_edit_profile.scss
ログインページのビューを修正
「私はロボットではありません」の部分が崩れていたため
=> Modify style of sign in page

app/views/mypages/completed_transaction.html.haml, app/views/mypages/in_transaction.html.haml, app/views/mypages/listing.html.haml, app/views/mypages/purchase.html.haml, app/views/mypages/purchased.html.haml
=> fixed-path

app/assets/javascripts/image_upload.js, app/views/shared/posts/edit/_image_upload.html.haml, app/views/shared/posts/edit/_previews.html.haml, app/views/shared/posts/form/_image_upload.html.haml
=> Modify image edit function
